export const ERROR_CODES = {
  INVALID_URL: "SM-URL-001",
  UNSUPPORTED_URL: "SM-URL-002",
  INSTAGRAM_NOT_FOUND: "SM-IG-101",
  INSTAGRAM_PRIVATE: "SM-IG-102",
  INSTAGRAM_MEDIA_UNAVAILABLE: "SM-IG-103",
  INSTAGRAM_RESOLVER_FAILED: "SM-IG-104",
  INSTAGRAM_UPSTREAM_CHANGED: "SM-IG-105",
  X_NOT_FOUND: "SM-X-101",
  X_PRIVATE: "SM-X-102",
  X_MEDIA_UNAVAILABLE: "SM-X-103",
  X_RESOLVER_FAILED: "SM-X-104",
  X_UPSTREAM_CHANGED: "SM-X-105",
  PINTEREST_NOT_FOUND: "SM-PIN-101",
  PINTEREST_PRIVATE: "SM-PIN-102",
  PINTEREST_MEDIA_UNAVAILABLE: "SM-PIN-103",
  PINTEREST_RESOLVER_FAILED: "SM-PIN-104",
  PINTEREST_UPSTREAM_CHANGED: "SM-PIN-105",
  REDDIT_NOT_FOUND: "SM-RD-101",
  REDDIT_PRIVATE: "SM-RD-102",
  REDDIT_MEDIA_UNAVAILABLE: "SM-RD-103",
  REDDIT_RESOLVER_FAILED: "SM-RD-104",
  REDDIT_UPSTREAM_CHANGED: "SM-RD-105",
  API_TIMEOUT: "SM-API-201",
  API_RATE_LIMITED: "SM-API-202",
  API_PAYLOAD_TOO_LARGE: "SM-API-203",
  BACKEND_UNAVAILABLE: "SM-SRV-301",
  FRONTEND_EXCEPTION: "SM-UI-401",
} as const;

export type SaveMingoErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export type PublicError = {
  code: SaveMingoErrorCode;
  message: string;
  requestId: string;
};
